### ISSUE TITLE
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/sercom#2]
Running src/main.py, I can view all the ports but I do not have permission to connect to it.

Exception:
```py
2022-04-23 16:40:34,931 - mvc.model - DEBUG - Attempting to connect to port /dev/ttyACM0
2022-04-23 16:40:34,932 - mvc.view - ERROR - Failed to connect to port /dev/ttyACM0!
Traceback (most recent call last):
  File "/home/ckyiu/sercom/venv/lib/python3.9/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ckyiu/sercom/src/mvc/view.py", line 209, in connect_to_port
    self.controller.connect(port)
  File "/home/ckyiu/sercom/src/mvc/controller.py", line 58, in connect
    self.model.connect(path)
  File "/home/ckyiu/sercom/src/mvc/model.py", line 59, in connect
    self.port = Serial(path)
  File "/home/ckyiu/sercom/venv/lib/python3.9/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/ckyiu/sercom/venv/lib/python3.9/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
```

**Comment by UnsignedArduino** [comment]
Following this [StackOverflow answer](https://stackoverflow.com/a/27886201), a solution is to add the current user to the `dialout` group, with `usermod -aG dialout <user>`. (`sudo` may be required) Then sign out and sign back in.
